services:
  web:
    build: ./go-http
    container_name: go-http
    ports:
      - "80:80"

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: nemida_db
      POSTGRES_USER: nemida_user
      POSTGRES_PASSWORD: "tujhrf,kznm"

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
