name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            APP_ENV=$(grep '^APP_ENV=' .env | cut -d '=' -f2)
            if [ "$APP_ENV" = "dev" ]; then
            ./scripts/up-prod
            else
            ./scripts/up-local
            fi
            git pull
              composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            ./scripts/migrate
            php artisan cache:clear


